FROM node:16.15-alpine

# set working directory
WORKDIR /app

# install app dependencies
COPY package.json ./
RUN npm cache clean --force
RUN npm install --loglevel verbose  --legacy-peer-deps 
#RUN npm install -f


COPY . .

# Expose port
EXPOSE 80
# start app
CMD [ "npm" , "start" ]
